### ISSUE TITLE
Threshold for jump detection is too low in some cases

### ISSUE THREAD

**Issue by ray66** [martin-ueding/geo-activity-playground#106]
When the time difference between two track points is greater than 30 seconds, the connection between the two points is not considered as part of the activity. No line is drawn on the map and tiles between the two points are not added to the explorer tile map. 

While this seems ok for sports-oriented activities like road cycling, the 30 seconds threshold is too low in many other use cases. Stops for taking pictures frequently exceed 30 seconds but should not be considered as activity breaks. Some devices have an option like "store location on significant change in direction only" which results in no points stored while moving on a straight line. This also may result in time difference between two points exceeding 30 seconds.

In order to prevent such breaks of activities, the time threshold should be either increased or made configurable.

Another solution would be to take into account the distance between the two points.

**Comment by martin-ueding** [comment]
With the changes from #90 I have also seen this in my own activities:

![visualization](https://github.com/martin-ueding/geo-activity-playground/assets/976924/bb36245a-bf3e-4f48-9c3c-6baaa71ce942)

And my Garmin watch is set such that it continuously records, without stopping for breaks. I'll have to look into it. But it indeed seems that the threshold is too low.

**Comment by martin-ueding** [comment]
The straight line thing is hard to do properly in order to prevent both false-positives and false-negatives.

I've now added an additional criterion that one must have a break longer than 30 s and also a jump of more than 100 m before it is considered a new segment. That should fix the issue with taking pictures, for instances.

It is not automatically applied to all existing activities, one would have to re-scan them.

I'll close this for now, but feel free to reopen when it doesn't solve your problem with version 0.21.0.
