### ISSUE TITLE
Add option to upload

### ISSUE THREAD

**Issue by ragnar76** [martin-ueding/geo-activity-playground#111]
i use the docker container and every time i want to add a new route or track i have to stop the container, copy files to the basedir and restart the container. it would be nice to have the possibility to upload files from the webinterface

**Comment by martin-ueding** [comment]
I totally understand the value in this. This is not going to be easy, unfortunately, because I started developing this with the mental model of it being just a viewer of a fixed set of activities. Adding activities interactively means that I have to perform some computations on them (which is fine) but then also update all the other things. I'll need to think about this for a while.

**Comment by martin-ueding** [comment]
I've implemented it and just released version 0.22.0. Please have a look whether that's suitable for you.

**Comment by ragnar76** [comment]
Will try when I'm back home

Martin Ueding ***@***.***> schrieb am So., 16. Juni 2024,
10:56:

**Comment by ragnar76** [comment]
Nope, the docker container does not work

`2024-06-16 10:33:47 geo_activity_playground.core.cache_migrations INFO Apply cache migration if needed …
Parse activity metadata: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 118/118 [00:00<00:00, 795.88it/s]
Collate activity metadata: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 118/118 [00:01<00:00, 100.98it/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/geo_activity_playground/__main__.py", line 118, in <module>
    main()
  File "/app/geo_activity_playground/__main__.py", line 93, in main
    options.func(options)
  File "/app/geo_activity_playground/__main__.py", line 67, in <lambda>
    *make_activity_repository(options.basedir, options.skip_strava),
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/geo_activity_playground/__main__.py", line 112, in make_activity_repository
    scan_for_activities(repository, tile_visit_accessor, config, skip_strava)
  File "/app/geo_activity_playground/webui/upload_controller.py", line 89, in scan_for_activities
    import_from_directory(
  File "/app/geo_activity_playground/importers/directory.py", line 81, in import_from_directory
    repository.commit()
  File "/app/geo_activity_playground/core/activities.py", line 90, in commit
    assert pd.api.types.is_dtype_equal(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: (dtype('O'), Timestamp('2024-06-10 05:52:21+0000', tz='UTC'))
`

**Comment by martin-ueding** [comment]
I've had the same thing. Can you delete the `Cache` directory and try again?

**Comment by ragnar76** [comment]
Finally some free time 🥳

It works! In fact, it works to good. It's open for all. I don't want you to write a complete user system but can you imagine to add some password based checks? Dunno, add a password inside the config file and chek if it matches, if not, uploads are discarded.

However, thank you for your support so far 😃

**Comment by martin-ueding** [comment]
That sounds like a reasonable quick way to protect it. I've added a password field:

![upload-form](https://github.com/martin-ueding/geo-activity-playground/assets/976924/36269339-d1c6-4ddc-96e6-da9bccb3d789)

It also supports KeePassXC browser plugin, so it should be relatively fine to use with password managers.

You need to explicitly configure it, otherwise you only see this:

![Bildschirmfoto_20240622_130900](https://github.com/martin-ueding/geo-activity-playground/assets/976924/8f6b4a51-8e46-47f8-9fa3-08fe1dcf2e40)

Put the following into your configuration file:

```toml
[upload]
password = "fb1c8d62-07a5-47bf-ada1-30aa66e41d8a"
```

It will be part of the 0.23.0 release. I think I'm going to hack for another hour or so, and then publish the release.

**Comment by ragnar76** [comment]
No hurry, I'm using Apaches "require IP" now which works great

Martin Ueding ***@***.***> schrieb am Sa., 22. Juni 2024,
13:14:
