### ISSUE TITLE
Number of new explored tiles is not displayed

### ISSUE THREAD

**Issue by beautiful-orca** [martin-ueding/geo-activity-playground#178]
The count of new explored tiles is not shown for an activity.

![Screenshot_20241005-125832_Iceraven](https://github.com/user-attachments/assets/3a1394f1-4075-4527-a8c6-82e627560130)

The map with the tiles is displayed correctly tho.

**Comment by martin-ueding** [comment]
Typical bug that I introduced during refactoring. It is fixed in the next version:

![Bildschirmfoto_20241013_084455](https://github.com/user-attachments/assets/4dd8eb6a-b474-416a-8956-4c69690a0959)

![Bildschirmfoto_20241013_084511](https://github.com/user-attachments/assets/076f1fc6-9794-461e-8051-2200a65f2c8c)

**Comment by beautiful-orca** [comment]
![Screenshot_20241014-003743_Iceraven](https://github.com/user-attachments/assets/9316ddf7-3296-4dfa-ab32-00bc7020217a)
Danke für den fix.
