### ISSUE TITLE
--skip-strava not working?

### ISSUE THREAD

**Issue by momentmal** [martin-ueding/geo-activity-playground#203]
I reached the long term API rate limit already trying to sync in my ~485 strava activities.
When adding --skip-strava to my .bat, i get an error. Is this meant to be used differently?

![image](https://github.com/user-attachments/assets/2867428f-bd46-43a5-b758-f15fe78076c9)

**Comment by martin-ueding** [comment]
Sorry about that. I've renamed it to `--skip-reload` a while ago and didn't update the documentation.

**Comment by martin-ueding** [comment]
The problem is that with the current approach, _all_ activities are gathered in an intermediate state before they are added. The reason is that in order to have proper explorer cluster and square history, the activities need to be processed in chronological order. Hence I collect all of them before adding them to the cluster.

This batch processing does have the disadvantage that you don't see anything until everything is imported. I am already considering to compromise with the explorer tile history in order to improve that. Not sure about it yet.

**Comment by momentmal** [comment]
I feel like it is a barrier that can feel super frustrating for someone new to to the project just trying to see a working server with a bunch of activities after having connected to strava API. 

I wasn't able to bring in my strava archive in via the 3 possible methods you are pointing out in 3 different areas of the documentation, so I was completely dependent on a successful API sync, which because of the rate limits automatically requires you to run the sync over a period of 2 days if you have more than 500 activities, and which had been  failing for me on my 2 attempts so far (missing activities), so it took me a lot of perseverance to stick to the project 😄👌 (basically whatched my machines running this task for 6 days now so far)
