### ISSUE TITLE
Idee: Potenziell nächstes Quadrat

### ISSUE THREAD

**Issue by Natenom** [martin-ueding/geo-activity-playground#36]
Ich weiß nicht, ob man sowas überhaupt machen kann, aber ne Funktion wäre interessant, die in der Kachelansicht anzeigt, wo potenziell ein Quadrat erschlossen werden könnte, wo z. B. nur noch weniger als x Kacheln fehlen. Hilft bei der Gamification.

**Comment by Oi-sin** [comment]
Sehr gute Idee! Bei StatsHunters gibt es das. Dort nennt sich das Square planner und sieht so aus: 
![image](https://github.com/martin-ueding/geo-activity-playground/assets/32384889/ba67ce89-609c-4a9c-a245-0a673af71e77)

**Comment by martin-ueding** [comment]
Ich fürchte, dass ein so schönes interface meine Fähigkeiten in Javascript etwas übersteigt. Ich hatte überlegt, was man ohne Nutzereingabe machen kann. Vielleicht jene Vergrößerung anbieten, bei der man die wenigsten zusätzlichen Kacheln braucht?

Allerdings ist es bei mir nicht hilfreich. Die offensichtlich nächste Kachel ist schlicht nicht erreichbar (Luftwaffen-Kaserne). Somit erscheint mir das eh immer eine Abwägung zu brauchen. Andere Kacheln bei mir sind an steilen Hängen.

Und bei den kleinen Kacheln wird es mit der Erreichbarkeit noch viel schwerer. Da gibt es teilweise bestimmte Grundstücke, auf die man gar nicht kommt. Die müsste man dann alle irgendwie explizit rausnehmen.

**Comment by martin-ueding** [comment]
I think that there is a need for manual input because there are so many individual things that an algorithm cannot know. There are tiles which cannot be explored at all, or there are certain places that one doesn't want to go to now. Perhaps one wants to be ambitious and plan for a rather large square directly.

I've just copied the design from Stats Hunters:

![Screenshot_20240203_204424](https://github.com/martin-ueding/geo-activity-playground/assets/976924/3db40b63-2e47-4dd8-aa2a-15982b66a880)

![Screenshot_20240203_204434](https://github.com/martin-ueding/geo-activity-playground/assets/976924/fadd3173-b6e4-4f44-8b24-5f55b4294d13)

It is not as smooth because it is implemented on the server side. But I think it works.

I think I'll implement something to download the missing tiles as GeoJSON and GPX, then one can directly go tile hunting.

**Comment by martin-ueding** [comment]
Done in 0.19.0.
