### ISSUE TITLE
Ability to compute all data (heatmap, explorer/14/17) at once

### ISSUE THREAD

**Issue by Natenom** [martin-ueding/geo-activity-playground#58]
Workflow now:
- Add new tracks
- run with `serve`
- open website `explorer/14` and `explorer/17` and wait very long with no information
- open heatmap and wait very long with no information

New workflow:
- Add new tracks
- run `geo-activity-playground --comput-all-data`
- drink a tea
- open local website and look around. :)

**Comment by martin-ueding** [comment]
I am also not sure what the best approach is. I'd call them _eager_ and _lazy_. Currently I have implemented the lazy style for some parts and the eager style for others. At the time it wasn't so clear which would be the best approach.

Now it becomes clearer and I think I will move more things to the eager evaluation.

The thing is that some things are easy to generate and aren't requested often:

- Individual heatmap tiles can be rendered on-demand and are cached. It is infeasible to compute them all in advance as there are just way too many tiles. Each tile takes 64 kiB and there are 274,877,906,944 tiles on level 19, so that would be 16 PiB of data.
- Share pictures for each activity are also quickly rendered.
- Downloading pixel tiles from Open Street Map.

But there are other things which we should compute in advance:

- Extract the time series data from GPX, FIT and TCX files.
- Take each activity and compute the tiles that it has explored.
- For each tile compute which activity has explored it, especially noting the first and last one.

I will try to shift the balance more towards the eager part. Perhaps it then also makes sense to add the progress bars back. With lazy evaluation the progress bars didn't make so much sense.

**Comment by martin-ueding** [comment]
I've changed how this works and converted more things to this _eager_ mode. The changes are on `master`. They work for me, so I hope that they also work for you. Could you please try it out?
